### ISSUE TITLE
Order sub-menu links

### ISSUE THREAD

**Issue by ollieanwyll** [ministryofjustice/cloud-platform-user-docs#29]
On the homepage, we need to figure out how to order the links under their categories.
Currently, it seems totally random. 

<img width="546" alt="screen shot 2018-05-10 at 13 37 34" src="https://user-images.githubusercontent.com/32272262/39869910-54e0ed10-5457-11e8-90a8-4b678c0957ce.png">

**Comment by kalbir** [comment]
## Background

They are sorted alpha-numerically by the name of the file for that page. So we can sort out the ordering by making the file names something like:

`1-env-creation.md`
`2-deploy-an-app.md`

etc. This *will* break links however as a) we've made most of the links hardcoded and b) the name of the page in the URL is the name of the file (so `/env-create` will become `/1-env-create`). So that's something to check when we do this. 

## Done when

- [ ] The homepage of the user documentation shows the pages in order of the user flow for the pages (i.e. "authenticating to a cluster "before "deploying an app")
