### ISSUE TITLE
Create a demo app to show file upload to S3

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform-user-docs#8]
**Estimate 2**

- [ ] Uploading a file without credentials fails
- [ ] Uploads a file
- [ ] Checks that the file is there

Suggested doing this as a Django app

**Comment by kerin** [comment]
I fear we're not being explicit enough about what some of these things mean, for instance:

> Uploading a file without credentials fails

That makes sense, but I don't think it implies that we then need to demonstrate low-level credential handling with S3 libraries. Credentials handling for AWS is pretty well defined and well understood, so our code should use sensible methods that are in common use (creds in env vars or IAM roles), and the Kubernetes deployment stuff can demonstrate what happens when the creds are missing - it's not something the app should be concerned with.

**Comment by kalbir** [comment]
Good point @kerin -- I expect we need to be clearer in these tasks. We captured the high level but not some of the detail that was in the dicussion. That means it can be less clear when you come back to it what exactly we are talking about. 

I've hopefully made some improvements in the newer ones. Let's see if we can make it better through the planning sessions.

On this one in particular -- "Updating a flie without credentials fails", I meant something like, if you haven't set the secret as a Kubernetes secret the file update will fail. But yes that should have been in here.

Hope that is helpful @razvan-moj.

**Comment by razvan-moj-zz** [comment]
https://github.com/ministryofjustice/cloud-platform-reference-app/pull/18
